const ACTIONS = Object.freeze({
  ANIMATION_OPTIONS: {
    POINTS: "ANIMATION_OPTIONS/POINTS",
    TIMES: "ANIMATION_OPTIONS/TIMES",
    INCREMENTS: "ANIMATION_OPTIONS/INCREMENTS",
    SPEED: "ANIMATION_OPTIONS/SPEED",
    FILL_COLOR: "ANIMATION_OPTIONS/FILL_COLOR",
    LINE_COLOR: "ANIMATION_OPTIONS/LINE_COLOR",
    LINE_WIDTH: "ANIMATION_OPTIONS/LINE_WIDTH",
    RAINBOW_EVERY_NTH_LINE: "ANIMATION_OPTIONS/RAINBOW_EVERY_NTH_LINE",
    COLORING_MODE: "ANIMATION_OPTIONS/COLORING_MODE",
  },
  ANIMATION_STATE: {
    START: "ANIMATION_STATE/START",
    RESET: "ANIMATION_STATE/RESET",
    PAUSE: "ANIMATION_STATE/PAUSE",
    RESUME: "ANIMATION_STATE/RESUME",
  },
});

const COLORING_MODES = Object.freeze({
  ALTERNATING: "ALTERNATING",
  RAINBOW: "RAINBOW",
  STATIC: "STATIC",
});

const SPEED_MODES = Object.freeze({
  VERY_FAST: "VERY_FAST",
  FAST: "FAST",
  NORMAL: "NORMAL",
  SLOW: "SLOW",
  VERY_SLOW: "VERY_SLOW",
  MANUAL: "MANUAL",
});

export { ACTIONS, COLORING_MODES, SPEED_MODES };
