const ACTIONS = Object.freeze({
  ANIMATION_OPTIONS: {
    POINTS: "ANIMATION_OPTIONS/POINTS",
    TIMES: "ANIMATION_OPTIONS/TIMES",
    INCREMENTS: "ANIMATION_OPTIONS/INCREMENTS",
    SPEED: "ANIMATION_OPTIONS/SPEED",
    FILL_COLOR: "ANIMATION_OPTIONS/FILL_COLOR",
    LINE_COLOR: "ANIMATION_OPTIONS/LINE_COLOR",
  },
  ANIMATION_STATE: {
    START: "ANIMATION_STATE/START",
    RESET: "ANIMATION_STATE/RESET",
    PAUSE: "ANIMATION_STATE/PAUSE",
    RESUME: "ANIMATION_STATE/RESUME",
  },
  ANIMATION_DATA: {
    UPDATE: "ANIMATION_DATA/UPDATE",
  },
});

export { ACTIONS };
